In [ ]:
#한줄주석
여러줄로
주석처리를
# ctrl / 를 클릭하면 여러줄 주석처리가능

'''
이렇게 여저줄로 주석처리
할수도 있어
'''

1+2
'''
ctrl + enter (실행)

shift + enter (마크다운)
'''

'''
ESC = 나가기

M = 마크다운으로 가는 기능

Y = 다시 파이선으로 가는 기능

B = 
'''

In [7]:
#안녕하세요
## 반갑습니다
### 

- 넘파이 실습

In [11]:
math=[12,23,12,14,15] #수학점수
eng=[32,12,31,54,67] #영어점수 

print(math+eng)

[12, 23, 12, 14, 15, 32, 12, 31, 54, 67]


In [15]:
# 리스트로 합 구하기

hap=[]
for i in range(len(math)): #0,1,2,3,4
    hap.append(math[i]+eng[i])
print(hap)

[44, 35, 43, 68, 82]


In [23]:
# 넘파이 배열로 합 구하기

import numpy as np

mathNum=np.array(math)
engNum=np.array(eng)

print(mathNum)
engNum


[12 23 12 14 15]


array([32, 12, 31, 54, 67])

In [25]:
mathNum+engNum

array([44, 35, 43, 68, 82])

In [30]:
heights=[1.68,17.76,1.59,1.86,1.73] # 키 단위 미터
weights=[70,82,52,92,79]


In [37]:
import numpy as np

np_height=np.array(heights)
np_weight=np.array(weights)


In [41]:
BMI=np_weight/(np_height**2)
print("대상자들의 BMI:")
BMI


대상자들의 BMI:


array([24.8015873 ,  0.25997281, 20.56880661, 26.59266967, 26.3958034 ])

# Pandas 예제실습

In [50]:
#Series 생성

import pandas as pd

num=[i for i in range(1,11)]

seriesNum=pd.Series(num)
seriesNum

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [55]:
# Series 요약통계

seriesNum.sum()
seriesNum.mean()
seriesNum.std()
seriesNum.median()

seriesNum.describe()

count    10.00000
mean      5.50000
std       3.02765
min       1.00000
25%       3.25000
50%       5.50000
75%       7.75000
max      10.00000
dtype: float64

In [60]:
# 딕셔너리 => 시리즈

num2=pd.Series({'a':1, 'b':2, 'c':3, 'd':4})
num2

a    1
b    2
c    3
d    4
dtype: int64

In [64]:
num2[0] #인덱스 번호로 추출
num2['c'] #인데스 이름으로 추출

/tmp/ipykernel_5215/3695153801.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num2[0] #인덱스 번호로 추출


3

- 결측치 확인

In [70]:
s=pd.Series([1,2,np.nan,4,5])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [73]:
#결측치 확인
s.isnull()
s.isnull().sum()

1

In [79]:
#결측치처리_채워넣기

s.isnull() #원본저장이 안됨
s.fillna(0,inplace=True) #원본저장이 됨
s

0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
dtype: float64

In [86]:
#결측치처리_삭제

a=pd.Series([1,2,np.nan,4,5,7,np.nan])
a
a.dropna()
a

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    7.0
6    NaN
dtype: float64

- Dataframe 생성

In [89]:
#데이터프레임 생

nums=[[1,2,3,],[4,5,6],[7,8,9]]
dfnums=pd.DataFrame(nums)
dfnums

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [97]:
# 정보
dfnums.shape #행렬정보
dfnums.shape[0]
dfnums[0].sum()
dfnums+3

0   1   2
0   4   5   6
1   7   8   9
2  10  11  12

In [100]:
# 행, 열별로 합계 구하기

dfnums.sum(axis=1) #가로방향 각 행별 합계
dfnums.sum(axis=0) #세로방향 각 행별 합계

0    12
1    15
2    18
dtype: int64

- 컬럼명 생성

In [109]:
users=[['철수',160,16],['민수',170,18],['짱구', 130,13],['영희',110,8]]
dfusers=pd.DataFrame(users)
dfusers

0    1   2
0  철수  160  16
1  민수  170  18
2  짱구  130  13
3  영희  110   8

In [111]:
# 컬럼명 생성

dfusers.columns=['name','height','age']
dfusers

name  height  age
0   철수     160   16
1   민수     170   18
2   짱구     130   13
3   영희     110    8

In [116]:
# 인덱스명 생성

dfusers.index=['학생1','학생2','학생3','학생4']
dfusers

name  height  age
학생1   철수     160   16
학생2   민수     170   18
학생3   짱구     130   13
학생4   영희     110    8

In [118]:
dfusers['height'].sum()

570

In [126]:
# 인덱스명으로 행추출

dfusers.loc['학생1']
dfusers.loc[['학생1','학생3']]
dfusers.loc['학생1','age']
dfusers.loc['학생3',['name','age']]

name    짱구
age     13
Name: 학생3, dtype: object

In [136]:
# 인게스번호로 행 추출

dfusers.iloc[0]
dfusers.iloc[[0,2]]
dfusers.iloc[[0,0]]

name  height  age  weight
학생1   철수     160   16      80
학생1   철수     160   16      80

- 새로울 열생성

In [137]:
dfusers['weight']=[80,67,30,17]
dfusers

name  height  age  weight
학생1   철수     160   16      80
학생2   민수     170   18      67
학생3   짱구     130   13      30
학생4   영희     110    8      17

In [ ]:
# 새로운 열생성 (위치지정 방법)

dfusers.insert(2,'Type',['A','B','O','AB'])
dfusers

In [160]:
# 부울링 인덱싱

dfusers['height'] >= 150
dfusers['Type'] == 'A'

학생1     True
학생2    False
학생3    False
학생4    False
Name: Type, dtype: bool

In [175]:
(dfusers['height'] >= 150) & (dfusers['weight'] <= 70) #and
(dfusers['height'] >= 150) | (dfusers['weight'] <= 70) #or

학생1    True
학생2    True
학생3    True
학생4    True
dtype: bool

In [182]:
# 정렬
dfusers.sort_values(by='age') #오름차순
dfusers.sort_values(by='age',ascending=False) #내림차순


name  height Type  age  weight
학생2   민수     170    B   18      67
학생1   철수     160    A   16      80
학생3   짱구     130    O   13      30
학생4   영희     110   AB    8      17

In [ ]:
# 열삭제

dfusers.drop('age',axis=1,inplace=True)
dfusers

# (axis=1) #가로방향 각 행별 합계
# (axis=0) #세로방향 각 행별 합계

In [ ]:
del dfusers['Type']
dfusers

- 람다 함수

In [3]:
(lambda x: 2*x)(2)


4